version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_USERNAME=${GIT_USERNAME}
        - GIT_PASSWORD=${GIT_PASSWORD}
    image: myapp:latest
    command: ["python3", "/app/your_script.py"]
