version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITCONFIG=${HOME}/.gitconfig
    image: myapp:latest
    command: ["python3", "/app/reqver/reqver/cli.py"]
