version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    command: ["python3", "/app/your_script.py"]
    volumes:
      - ${HOME}/.gitconfig:/root/.gitconfig:ro
